user:
  email:
    max_length: 255
    email_regex: !ruby/regexp '/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i'
  password:
    min_length: 6
  name:
    max_length: 50
admin:
  room:
    name:
      max_length: 50
    description:
      max_length: 5000
    greater:
      min_length: 0
    less:
      max_length: 1000000
  room_view:
    name:
      max_length: 100
    pagy:
      max_length: 10
    new:
      description:
        max_length: 5000
      price:
        min: 0
      name:
        max_length: 50
models:
  room: [80, 90]
  images_format: ["image/jpeg", "image/gif", "image/png"]
  image_size: 25MB
